version: '3.7'
services:
  nats:
    image: nats
  redis:
    image: redis:alpine
  test:
    build:
      context: "."
      args:
        PKGNAME: "nats"
    depends_on:
      - nats
      - redis
    volumes:
      - ".:/opt/code"
