version: '3.7'
services:
  nats:
    image: nats
  redis:
    image: redis:alpine
  nats-test:
    build:
      context: "."
      dockerfile: "./nats/Dockerfile"
    depends_on:
      - nats
    volumes:
      - ".:/opt/code"
  redis-test:
    build:
      context: "."
      dockerfile: "./redis/Dockerfile"
    depends_on:
      - redis
    volumes:
      - ".:/opt/code"
